contact_links:
  - name: Are you looking for documentation on stadtgeschichtebasel.ch?
    url: https://github.com/Stadt-Geschichte-Basel/stadtgeschichtebasel.ch
    about: Please see the documentation for stadtgeschichtebasel.ch on its GitHub Pages page.
  - name: Do want to discuss stadtgeschichtebasel.ch with the community?
    url: https://github.com/Stadt-Geschichte-Basel/stadtgeschichtebasel.ch/discussions
    about: Please see the discussions page for stadtgeschichtebasel.ch.
blank_issues_enabled: true
